# .github/workflows/repomap.yml
name: Generate Aider RepoMap
on:
  push:
    paths: 
      - ".github/workflows/repomap.yml"
  workflow_dispatch:

jobs:
  respond-to-issue:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dependencies...
        run: |
          python -m pip install --upgrade pip
          pip install aider-chat
        
      - name: Build Repo Map
        run: python -m aider.repomap *
